project_id = "pkdwemunxxpafpmiqxiq"

[functions.whatsapp-sender]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.optimize-route]
verify_jwt = false

[functions.get-maps-key]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.subscription-cleanup]
verify_jwt = false

[functions.purchase-timbres]
verify_jwt = false

[functions.manage-subscription]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.billing-notify-email]
verify_jwt = false

[functions.purchase-route-credits]
verify_jwt = false

[functions.verify-route-credits]
verify_jwt = false

[functions.daily-billing]
verify_jwt = false
